version: '2'
services:
  rancher-master:
    container_name: rancher-master
    image: rancher/server:stable
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./var/rancher-master/mysql:/var/lib/mysql
