version: '2'
services:

  php:
    labels:
      traefik.domain: 'symfony1.local'
      traefik.port: 80
      traefik.enable: true
      traefik.frontend.rule: 'Host:symfony1.local'
    health_check:
      port: 80
      interval: 2000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      response_timeout: 10000
      request_line: GET "/" "HTTP/1.0"
      healthy_threshold: 2
